{
    "name": "Document Invoice HDS Metalica",
    "summary": """Formatos de facturas para la empresa HDS Metalica""",
    "version": "13.0.1.0.0",
    "description": """Formatos de facturas para la empresa HDS Metalica""",
    "author": "Manuel Calero",
    "company": "Xtendoo",
    "website": "http://xtendoo.es",
    "category": "Extra Tools",
    "depends": [
        "base",
        "account",
        "product",
        "account_tax_balance",
        "report_qweb_element_page_visibility",
        ],
    "license": "AGPL-3",
    "data": [
        "views/layout/external_layout_invoice.xml",
        "views/layout/external_layout_sale.xml",
        "views/invoice/invoice_document.xml",
        "views/sale_order/sale_order_document.xml",
    ],
    "installable": True,
    "auto_install": False,
}
